name: Rust CI

on:
  push:
    branches: ["*"]
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - ".gitignore"
      - "LICENSE-*"
      - "COPYRIGHT"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - ".gitignore"
      - "LICENSE-*"
      - "COPYRIGHT"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  lint-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt, clippy, llvm-tools-preview

      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Format & clippy checks
        run: |
          cargo fmt --all -- --check
          cargo clippy --workspace --all-features -- -D warnings
        continue-on-error: true

      - name: Build & run tests
        run: |
          cargo test --workspace --all-features --no-run
          cargo nextest run --all-features

  
  coverage:
    needs: lint-test-coverage
    if: ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.83.0
          components: rustfmt, clippy, llvm-tools-preview

      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Generate coverage (llvm-cov)
        run: |
          mkdir -p coverage
          cargo llvm-cov --workspace --all-features --lcov --output-path coverage/lcov.info

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5.4.2
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: true

  docs:
    needs: lint-test-coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: Swatinem/rust-cache@v2

      - name: Build docs
        env:
          RUSTFLAGS: "${{ env.RUSTFLAGS }} --cfg docsrs"
          RUSTDOCFLAGS: "--cfg docsrs"
        run: cargo doc --workspace --all-features --no-deps --document-private-items
