name: Rust CI

on:
  push:
    branches: ['*']
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '.gitignore'
      - 'LICENSE-*'
      - 'COPYRIGHT'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '.gitignore'
      - 'LICENSE-*'
      - 'COPYRIGHT'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  lint-test-cov:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt,clippy,llvm-tools-preview
        
    - name: Configure sccache
      uses: mozilla-actions/sccache-action@v0.0.4

    - uses: Swatinem/rust-cache@v2

    - name: Install cargo-nextest
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-nextest

    - name: Format & clippy checks
      run: |
        cargo fmt --all -- --check || true
        cargo clippy --workspace --all-features -- -D warnings
      continue-on-error: true

    - name: Build & run tests
      run: |
        cargo test --workspace --all-features --no-run
        cargo nextest run --all-features


    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-llvm-cov


    - name: Generate coverage (llvm-cov)
      run: |
        cargo llvm-cov --workspace --all-features --lcov --output-path ./coverage/lcov.info

    - name: Upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage/lcov.info
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: Kevinzh0C/flash-kv
        fail_ci_if_error: true

  macos-tests:
    runs-on: macos-latest
    needs: lint-test-cov   # Can stop early if Ubuntu main workflow fails

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: Swatinem/rust-cache@v2
    - name: Run tests on macOS
      run: cargo test --workspace --all-features --verbose

  docs:
    runs-on: ubuntu-latest
    needs: lint-test-cov

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: Swatinem/rust-cache@v2
    - name: Build docs
      run: cargo doc --workspace --all-features --no-deps --document-private-items
      env:
        RUSTFLAGS: ${{ env.RUSTFLAGS }} --cfg docsrs
        RUSTDOCFLAGS: --cfg docsrs -Dwarnings
